/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/favoriteScreen`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/mapScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../components/maps/MapParent`; params?: Router.UnknownInputParams; } | { pathname: `/userName`; params?: Router.UnknownInputParams; } | { pathname: `/../logic/create_new_track`; params?: Router.UnknownInputParams; } | { pathname: `/../models/TrackList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/maps/RaceMap`; params?: Router.UnknownInputParams; } | { pathname: `/../test/example-geometry-decoded`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/favoriteScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/mapScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/maps/MapParent`; params?: Router.UnknownOutputParams; } | { pathname: `/userName`; params?: Router.UnknownOutputParams; } | { pathname: `/../logic/create_new_track`; params?: Router.UnknownOutputParams; } | { pathname: `/../models/TrackList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/maps/RaceMap`; params?: Router.UnknownOutputParams; } | { pathname: `/../test/example-geometry-decoded`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/favoriteScreen${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/mapScreen${`?${string}` | `#${string}` | ''}` | `/../components/maps/MapParent${`?${string}` | `#${string}` | ''}` | `/userName${`?${string}` | `#${string}` | ''}` | `/../logic/create_new_track${`?${string}` | `#${string}` | ''}` | `/../models/TrackList${`?${string}` | `#${string}` | ''}` | `/../components/maps/RaceMap${`?${string}` | `#${string}` | ''}` | `/../test/example-geometry-decoded${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/favoriteScreen`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/mapScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../components/maps/MapParent`; params?: Router.UnknownInputParams; } | { pathname: `/userName`; params?: Router.UnknownInputParams; } | { pathname: `/../logic/create_new_track`; params?: Router.UnknownInputParams; } | { pathname: `/../models/TrackList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/maps/RaceMap`; params?: Router.UnknownInputParams; } | { pathname: `/../test/example-geometry-decoded`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
